### ISSUE TITLE
タイトル画面のシーンとゲーム終了時のシーンの作成

### ISSUE THREAD

**Issue by fujishimatakumi** [fujishimatakumi/simplefps#19]
タイトル画面とゲームが終了した時に移行するシーンを作成してください

考えている流れは
タイトル画面→ゲームシーン→終了画面→タイトル画面のループです

コメントに実装方法と作業ブランチ名を記載して作業を開始してください

**Comment by motegi45** [comment]
シーンを作り、UIを配置しておきます

ブランチ名は[sceneroop]で作業します

**Comment by motegi45** [comment]
終了しました
