### ISSUE TITLE
走る機能の実装

### ISSUE THREAD

**Issue by fujishimatakumi** [fujishimatakumi/simplefps#8]
キャラクターの移動速度がshiftキーを押している間速くなる機能を実装してください

コメントに実装方法と作業ブランチ名を書いてください

**Comment by motegi45** [comment]
「NetworkPlayerController」をいじります
「input」を使う
ブランチ名は「dash」にします

**Comment by motegi45** [comment]
終わりました

**Comment by motegi45** [comment]
終わりました
